trigger: none

parameters:
  - name: Services
    type: object
    default:
      - azure-keyvault-secrets
      - azure-keyvault-certificates

extends:
    template: /eng/pipelines/templates/stages/archetype-sdk-tests.yml
    parameters:
      ServiceDirectory: keyvault
      Packages: ${{ parameters.Services }}
      SupportedClouds: 'Public,UsGov,China'
      TestTimeoutInMinutes: 240
      UseFederatedAuth: true
      CloudConfig:
        Public:
          SubscriptionConfiguration: $(sub-config-azure-cloud-test-resources)
          ServiceConnection: azure-sdk-tests
          SubscriptionConfigurationFilePaths:
            - eng/common/TestResources/sub-config/AzurePublicMsft.json
        UsGov:
          SubscriptionConfiguration: $(sub-config-gov-test-resources)
          MatrixFilters:
            - ArmTemplateParameters=^(?!.*enableHsm.*true)
        China:
          SubscriptionConfiguration: $(sub-config-cn-test-resources)
          MatrixFilters:
            - ArmTemplateParameters=^(?!.*enableHsm.*true)
          Location: chinaeast2
      EnvVars:
        AZURE_TEST_RUN_LIVE: true
        AZURE_SKIP_LIVE_RECORDING: 'True'
        AZURE_SUBSCRIPTION_ID: $(azure-subscription-id)
        AZURE_CLIENT_OID: $(aad-azure-sdk-test-client-oid)
